# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_squashed_0008_attachment_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentrevision',
            name='is_s3_migrated',
            field=models.BooleanField(db_index=True, default=False, help_text=b'Has this revision been migrated to S3?'),
        ),
    ]
